### PR TITLE
Extend reader to read ATSR-2 files.

### PR DESCRIPTION
**Pull request by adamcpovey**
Some years ago, @caropoulsen2 made a very basic patch of this API to allow permit the opening of ATSR-2 files, which eliminated a dependency from our code. I offer it here should other users be interested. If you'd prefer to keep things to ENVISAT only, feel free to leave this PR unresolved. Also, I'd quite like to know if it does anything particularly stupid, though we haven't noticed any issues in the last few years of use.

### CODE REVIEW

**Comment by avalentino** [comment]
Hi @adamcpovey to me it makes sense to merge this PR event if it is not ENVISAT.
At a very first look the PR looks good.
Just few comments/requests:
* please add and entry in the change-log and relevent parts of the documentation if necessary
* It would like to give it a try, could you please point me to a freely accessible ASTR-2 product (the smaller the better)
* if you have some test code (in C or Python + pyepr) please share it

**Comment by adamcpovey** [comment]
Sorry it took me a while to get back to this.

- I didn't see any of the variables we changed in the documentation, so I just added a note to the top that ATSR-2 in ENVISAT format are supported.
- I bumped the third version number as this seems to minor to jump to 2.4. Change change that if you'd prefer.
- The smallest ATSR-2 file I could find can be downloaded [here](https://eodg.atm.ox.ac.uk/user/povey/AT2_TOA_1PURAL20020415_110053_000000001073_00093_36520_0000.E2). I'll delete it once you confirm download as there's a non-commercial license on these. The file doesn't appear to contain valid radiance but you can fetch things like latitude.

I also have a feedstock for compiling this in conda, should you have any interest in that.

**Comment by avalentino** [comment]
Hi @adamcpovey unfortunately I'm not able to download the ATSR'2 data 
```
Forbidden

You don't have permission to access this resource.
```

Maybe you could try with we-transfer or something like that.

Also I think that there is some backward compatibility problem.
Dome of the tests fail.
I have just added a small test script to demonstrate the problem.

**Comment by avalentino** [comment]
Hi @adamcpovey unfortunately I'm not able to download the ATSR'2 data 
```
Forbidden

You don't have permission to access this resource.
```

Maybe you could try with we-transfer or something like that.

Also I think that there is some backward compatibility problem.
Dome of the tests fail.
I have just added a small test script to demonstrate the problem.

**Comment by adamcpovey** [comment]
Could you try the download link again? I fell foul of restrictive default permissions.

I see your point about that test script but, in my defence, I get the exact same output on a clean repository:

> atmlxdt054:~/lib/gfortran_scratch/epr-api/build/bccunit/src$ ./bccunit_test 
> bccunit: running test suite "test_suite_1" containing 4 test(s)
> bccunit:   running test case "test_case_1"
> bccunit:   running test case "test_case_2"
> bccunit:   running test case "test_case_3"
> bccunit: failure: file /data/povey/lib/gfortran_scratch/epr-api/bccunit/src/bccunit_test.c: line 24: (3) == (get_3())
> bccunit:   running test suite "test_suite_2" containing 1 test(s)
> bccunit:     running test case "test_case_4"
> bccunit: failure: file /data/povey/lib/gfortran_scratch/epr-api/bccunit/src/bccunit_test.c: line 32: (3) == (get_3())
> bccunit: test summary: 4 test case(s) total, 2 failure(s), 0 error(s)

I have been running `make test` in my build, but that reports these scripts are passing. (I'm using cmake but just checked the configure version too.)

**Comment by avalentino** [comment]
@adamcpovey I'm now able to download your product, thanks.

Regarding tests, the cmake test is not complete actually.

If I run the test script in you r branch I get the following error:

```sh
+ ./api_unit_tests
I 2022/08/07 14:13:54 - ENVISAT Product Reader API, version 2.3.1
I 2022/08/07 14:13:54 - API successfully initialized
D 2022/08/07 14:13:54 - running on a little endian order architecture


I 2022/08/07 14:13:54 - ENVISAT product reader API is being closed
+ ./epr_performance_test ../../testdata/MER_RR__2PNRAL20100429_160201_000003102089_00040_42679_0001.N1
E 2022/08/07 14:13:54 - epr_create_flag_coding: unknown flag coding
E 2022/08/07 14:13:54 - epr_create_band_ids: out of memory
Error opening product ../../testdata/MER_RR__2PNRAL20100429_160201_000003102089_00040_42679_0001.N1: (null)
```

The script returns with a non-zero exit code:

```sh
$ echo $?
1
```

**Comment by adamcpovey** [comment]
How about that?

Unrelated question: why is `bccuint_test` [designed to fail](https://github.com/bcdev/epr-api/blob/b55154e62a0cf5163d3b17efe51dbec89e8755e8/bccunit/src/bccunit_test.c#L16) by returning two rather than three?

**Comment by avalentino** [comment]
Thanks @adamcpovey, I have merged the PR.

> Unrelated question: why is bccuint_test [designed to fail](https://github.com/bcdev/epr-api/blob/b55154e62a0cf5163d3b17efe51dbec89e8755e8/bccunit/src/bccunit_test.c#L16) by returning two rather than three?

I don't know, sorry.
Those are test for at test library.
Maybe it is just a way to check that the errors are properly detected by the test library.

**Pull request merged**
