### PR TITLE
Owen Embury's changes specific to ATSRs

### PR DESCRIPTION
**Pull request by flar**

### CODE REVIEW

**Comment by flar** [comment]
Hi contributors,

could you review the changes includes in these pull request? From my point of view they are fine and I would like to merge it, since I would need these changes for SST CCI project.

Thanks,
Ralf

**Comment by avalentino** [comment]
Hi @flar, I checked out the oembury:master branch, merged with bcdev:master and tested with pyepr.

Unfortunately the new branch breaks my tests and causes a segmentation fault:

```
env PYTHONPATH=. python3 tests/test_all.py --verbose
PyEPR: 0.9.3.dev0
EPR API: 2.3
Python: 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2]
test_data_property (__main__.TestAnnotatedRasterRead) ... skipped 'buggy EPR_C_API detected'
test_data_property_data_scope (__main__.TestAnnotatedRasterRead) ... *** Error in `python3': malloc(): memory corruption (fast): 0x0000000002b6c1c0 ***
Makefile:79: set di istruzioni per l'obiettivo "check" non riuscito
make: *** [check] Annullato (creato dump del core)
```

For this reason I'm -1 for merging this PR as is.

**Comment by flar** [comment]
OK - I'll close the request.

**Comment by oembury** [comment]
I suspect the problem is in c649f1530b656dcb934152b41284d006a01eba0c as I assume 32 pixels per tie-point (as used for ATSR)

**Pull request closed without merging**
